language: rust
sudo: false
cache:
  directories:
    - $HOME/.cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
branches:
  only:
    - master
    - staging
    - trying
script:
  - cargo build -v --features strict
  - cargo test -v --features strict
  - bash scripts/test_features.sh
  - cargo doc
after_success:
  - sh scripts/upload_doc.sh